engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
    exclude_fingerprints:
    - ee0a31701f95b21db4aff40647a56a3d
    - b86af833d6b2b1fa18da63471e2278d9
    - cdc1cac1f5cb7afe72dca9f9bca8a237
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.rake"
exclude_paths:
- spec/**/*
