engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
    exclude_fingerprints:
    - 4e9778929cc70d7e78ca70e2d8f9c682
    - 86689510a566f70822d4ae5319d845fa
    - 1b442713191d345ee4ef24f270926bd5
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.rake"
exclude_paths:
- spec/**/*
