version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.rake"
  - "Rakefile"
exclude_paths:
- bin/**/*
- icons/**/*
- spec/**/*
- ".gitignore"
- ".rspec"
- ".rubocop.yml"
- ".travis.yml"
- "LICENSE.md"
- "README.md"
