language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.2
  - 2.1
  - 2.0.0
  - rbx-2
addons:
  code_climate:
    repo_token: c19f4a2a864567e4dbf3e325b4423d9478c3bf025d9e3f85c6e2ffc0c9fb960f
before_install: gem install bundler -v 1.11.2
