---
language: ruby
cache: bundler
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
matrix:
  include:
    - rvm: 2.5.1
      after_success: bundle exec codeclimate-test-reporter

addons:
  code_climate:
    repo_token: c19f4a2a864567e4dbf3e325b4423d9478c3bf025d9e3f85c6e2ffc0c9fb960f

before_install: gem update bundler
